services:
  - type: web
    name: bodytech
    runtime: image
    repo: https://github.com/laurakkkkk/bodytech
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
